### ISSUE TITLE
locale file missing

### ISSUE THREAD

**Issue by ambrooo** [InfectoOne/vue-ganttastic#1]
When I compile I receive this warning:
`Module not found: Error: Can't resolve './locale' in '/Path/to/node_modules/node_modules/vue-ganttastic/dist'
`
on line 1908 you have this function which requires a locale directory:
`function loadLocale(name) {
    var oldLocale = null;
    // TODO: Find a better way to register and load all the locales in Node
    if (!locales[name] && (typeof module !== 'undefined') &&
            module && module.exports) {
        try {
            oldLocale = globalLocale._abbr;
            var aliasedRequire = require;
            aliasedRequire('./locale/' + name);
            getSetGlobalLocale(oldLocale);
        } catch (e) {}
    }
    return locales[name];
}`

**Comment by InfectoOne** [comment]
If I am not mistaken, this error happens if you do not have the [Moment.js](https://momentjs.com/) node module installed in your project. Installing vue-ganttastic _should_ automatically install Moment.js as well, because it is listed as a dependency. 

I will look into this problem and see why that may not have happened in your case. In the meantime, you may try installing Moment.js manually:
`npm install moment`

That might be a temporary workaround.

**Comment by InfectoOne** [comment]
The problem seems to occur upon bundling the Vue-Ganttastic package together with it's dependencies (among which is Moment.js). As a result, the `locale` prop of `<g-gantt-chart>` was not working correctly in the bundled version.

I have solved the problem in  commit f5edfb0 by listing Moment.js as a peer-dependency. This means that from now on users have to install moment.js by themselves manually using: 
`npm install moment`  

This seems a bit nagging at first, but has several advantages, among which are reduced bundle size, lesser error-proneness (especially if you already use Moment.js in your project, which is often the case).
