### ISSUE TITLE
Change format of secondary time axis

### ISSUE THREAD

**Issue by d11-kmann** [InfectoOne/vue-ganttastic#59]
I have tried setting a time unit slot but it doesn't seem to have an effect. What is required in the label and value parts.  Could this be added to the documentation please?

**Comment by InfectoOne** [comment]
You will have to use the `timeunit` slot and parse the `label` using e.g. `dayjs`:
```vue
<g-gantt-chart
...
>
...
  <template #timeunit="{ label, value }"> 
       // format "label" here
   </template>
  ....
</g-gantt-chart>
```
You could also parse and format `value`, but currently, value simply stands for the underlying dayjs-value unit (e.g.  for the label `March 2020` if secondary time axis stands for months, the value is `2`(since March is the 2nd month of the year, if couting from 0).
